name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy backend files to vps
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.SSH_USERNAME }}/stocktrader"
